<?php

namespace Omnipay\Mpgs\Enums;

/**
 * Class StatusEnum.
 */
class StatusEnum
{
    const AUTHENTICATED = 'AUTHENTICATED';
    const AUTHENTICATION_INITIATED = 'AUTHENTICATION_INITIATED';
    const AUTHENTICATION_NOT_NEEDED = 'AUTHENTICATION_NOT_NEEDED';
    const AUTHENTICATION_UNSUCCESSFUL = 'AUTHENTICATION_UNSUCCESSFUL';
    const AUTHORIZED = 'AUTHORIZED';
    const CANCELLED = 'CANCELLED';
    const CAPTURED = 'CAPTURED';
    const CHARGEBACK_PROCESSED = 'CHARGEBACK_PROCESSED';
    const DISBURSED = 'DISBURSED';
    const DISPUTED = 'DISPUTED';
    const EXCESSIVELY_REFUNDED = 'EXCESSIVELY_REFUNDED';
    const FAILED = 'FAILED';
    const FUNDING = 'FUNDING';
    const INITIATED = 'INITIATED';
    const PARTIALLY_CAPTURED = 'PARTIALLY_CAPTURED';
    const PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED';
    const REFUNDED = 'REFUNDED';
    const REFUND_REQUESTED = 'REFUND_REQUESTED';
    const VERIFIED = 'VERIFIED';
}
